title: DevNotes
description: A brief collection of personally assembled notes
repository: akshitv2/DevNotes
remote_theme: just-the-docs/just-the-docs

permalink: pretty
search_enabled: false
include_head: false
heading_anchors: true
author: Akshit